// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ7eefZxUgD1gXc7fAQwqp_bZYD4_keeA',
    appId: '1:244761038668:web:0bfb0ba2e703fb169689e9',
    messagingSenderId: '244761038668',
    projectId: 'dgacengy',
    authDomain: 'dgacengy.firebaseapp.com',
    storageBucket: 'dgacengy.appspot.com',
    measurementId: 'G-3PP904C4G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuU0anQ_bLzvH3w75TmLcE1uNPwLLvi8E',
    appId: '1:244761038668:android:4fd93b11305d71269689e9',
    messagingSenderId: '244761038668',
    projectId: 'dgacengy',
    storageBucket: 'dgacengy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM0XW_yPxgq6UdBg_e4QkOcV3YZkSvUwo',
    appId: '1:244761038668:ios:d0137934ffbcfe8f9689e9',
    messagingSenderId: '244761038668',
    projectId: 'dgacengy',
    storageBucket: 'dgacengy.appspot.com',
    iosBundleId: 'br.com.dgagency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM0XW_yPxgq6UdBg_e4QkOcV3YZkSvUwo',
    appId: '1:244761038668:ios:d0137934ffbcfe8f9689e9',
    messagingSenderId: '244761038668',
    projectId: 'dgacengy',
    storageBucket: 'dgacengy.appspot.com',
    iosBundleId: 'br.com.dgagency',
  );
}
